// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Account =
  | ({ type: "offline" } & OfflineAccount)
  | ({ type: "microsoft" } & MicrosoftAccount);

export type DeviceCodeResponse = {
  userCode: string;
  deviceCode: string;
  verificationUri: string;
  expiresIn: number;
  interval: number;
  message: string | null;
};

export type MicrosoftAccount = {
  username: string;
  uuid: string;
  accessToken: string;
  refreshToken: string | null;
  expiresAt: number;
};

export type MinecraftProfile = { id: string; name: string };

export type OfflineAccount = { username: string; uuid: string };

export type TokenResponse = {
  access_token: string;
  refresh_token: string | null;
  expires_in: number;
};
