// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AssistantConfig = {
  enabled: boolean;
  llmProvider: string;
  ollamaEndpoint: string;
  ollamaModel: string;
  openaiApiKey: string | null;
  openaiEndpoint: string;
  openaiModel: string;
  systemPrompt: string;
  responseLanguage: string;
  ttsEnabled: boolean;
  ttsProvider: string;
};

/**
 * Feature-gated arguments configuration
 */
export type FeatureFlags = {
  /**
   * Demo user: enables demo-related arguments when rules require it
   */
  demoUser: boolean;
  /**
   * Quick Play: enable quick play arguments
   */
  quickPlayEnabled: boolean;
  /**
   * Quick Play singleplayer world path (if provided)
   */
  quickPlayPath: string | null;
  /**
   * Quick Play singleplayer flag
   */
  quickPlaySingleplayer: boolean;
  /**
   * Quick Play multiplayer server address (optional)
   */
  quickPlayMultiplayerServer: string | null;
};

export type LauncherConfig = {
  minMemory: number;
  maxMemory: number;
  javaPath: string;
  width: number;
  height: number;
  /**
   * Concurrent download threads. Clamped via MIN_DOWNLOAD_THREADS/MAX_DOWNLOAD_THREADS.
   */
  downloadThreads: number;
  customBackgroundPath: string | null;
  enableGpuAcceleration: boolean;
  enableVisualEffects: boolean;
  activeEffect: string;
  theme: string;
  logUploadService: string;
  pastebinApiKey: string | null;
  assistant: AssistantConfig;
  useSharedCaches: boolean;
  keepLegacyPerInstanceStorage: boolean;
  featureFlags: FeatureFlags;
  /**
   * Download mirror source: "official", "bmclapi", "mcbbs"
   */
  mirrorSource: string;
  /**
   * Language / locale code: "auto", "zh-CN", "en"
   */
  language: string;
  /**
   * Enable system tray (minimize to tray)
   */
  enableSystemTray: boolean;
  /**
   * Hide the launcher window instead of exiting when the close button is used.
   */
  closeToTray: boolean;
  /**
   * Start with the launcher window hidden when the system tray is enabled.
   */
  startMinimizedToTray: boolean;
  /**
   * Hide the launcher after Minecraft starts successfully.
   */
  minimizeToTrayAfterLaunch: boolean;
  /**
   * Whether the guided tour has been completed
   */
  firstLaunchCompleted: boolean;
  /**
   * JVM optimization preset: "default", "g1gc", "zgc", "shenandoah"
   */
  jvmPreset: string;
  /**
   * GitHub download proxy URL, e.g. "https://ghproxy.hydroroll.team"
   * When non-empty, GitHub release download URLs will be proxied through this.
   */
  githubProxy: string;
};
