// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Instance } from "./instance";

export type ContentKind = "mod" | "resourcePack" | "shaderPack" | "dataPack";

export type ConversionApplyRequest = {
  instanceId: string;
  newName: string;
  target: ConversionTarget;
  excludedPaths: Array<string>;
};

export type ConversionDisposition =
  | "keep"
  | "replace"
  | "needsReview"
  | "incompatible";

export type ConversionItem = {
  relativePath: string;
  fileName: string;
  contentKind: ContentKind;
  sha1: string;
  sourceLoader: string | null;
  disposition: ConversionDisposition;
  reason: string;
  project: ConversionProject | null;
  replacement: ConversionReplacement | null;
  suggestion: ConversionSuggestion | null;
};

export type ConversionPreview = {
  sourceGameVersion: string;
  sourceLoader: string;
  target: ConversionTarget;
  items: Array<ConversionItem>;
  summary: ConversionSummary;
  sourceProtected: boolean;
  lookupWarnings: Array<string>;
};

export type ConversionProject = { id: string; name: string; pageUrl: string };

export type ConversionReplacement = {
  projectId: string;
  projectName: string;
  versionId: string;
  versionName: string;
  fileName: string;
  fileUrl: string;
  pageUrl: string;
};

export type ConversionReplacementTask = {
  relativePath: string;
  replacement: ConversionReplacement;
};

export type ConversionReport = {
  operationId: string;
  sourceInstanceId: string;
  targetInstance: Instance;
  preview: ConversionPreview;
  excludedPaths: Array<string>;
  replacedPaths: Array<string>;
  canRollback: boolean;
};

export type ConversionSuggestion = {
  projectId: string;
  projectName: string;
  pageUrl: string;
  reason: string;
};

export type ConversionSummary = {
  total: number;
  keep: number;
  replace: number;
  needsReview: number;
  incompatible: number;
};

export type ConversionTarget = {
  gameVersion: string;
  loader: string;
  loaderVersion: string | null;
};

export type PreparedConversionContent = {
  excludedPaths: Array<string>;
  replacements: Array<ConversionReplacementTask>;
};
