// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A unified content project returned from search results (Modrinth or CurseForge).
 */
export type ContentProject = {
  id: string;
  slug: string;
  title: string;
  description: string;
  iconUrl: string | null;
  /**
   * One of: mod, modpack, shader, resourcepack, datapack, plugin
   */
  projectType: string;
  downloads: bigint;
  follows: number;
  categories: Array<string>;
  gameVersions: Array<string>;
  loaders: Array<string>;
  /**
   * "modrinth" or "curseforge"
   */
  source: string;
  pageUrl: string;
  author: string;
  dateModified: string;
};

/**
 * Search result wrapper with pagination info.
 */
export type ContentSearchResult = {
  hits: Array<ContentProject>;
  totalHits: number;
  offset: number;
  limit: number;
};

/**
 * A single version/file of a content project.
 */
export type ContentVersion = {
  id: string;
  projectId: string;
  name: string;
  versionNumber: string;
  gameVersions: Array<string>;
  loaders: Array<string>;
  fileUrl: string;
  fileName: string;
  fileSize: bigint;
  datePublished: string;
};
