// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JavaInstallation } from "./java/core";
import type { MemoryAllocation } from "./memory";

/**
 * File information for instance file browser
 */
export type FileInfo = {
  name: string;
  path: string;
  isDirectory: boolean;
  size: number;
  modified: number;
};

export type GameExitedEvent = {
  instanceId: string;
  versionId: string;
  exitCode: number | null;
  wasStopped: boolean;
};

export type GithubRelease = {
  tagName: string;
  name: string;
  publishedAt: string;
  body: string;
  htmlUrl: string;
};

/**
 * Installed version info
 */
export type InstalledVersion = { id: string; type: string };

/**
 * The launch-critical checks used by the home command center.
 *
 * Java resolution intentionally reuses the same priority and compatibility
 * rules as `start_game`, so the UI cannot report a false-ready state.
 */
export type LaunchReadiness = {
  versionInstalled: boolean;
  requiredJavaMajor: number | null;
  java: JavaInstallation | null;
  memory: MemoryAllocation;
};

/**
 * Migrate instance caches to shared global caches
 */
export type MigrationResult = {
  movedFiles: number;
  hardlinks: number;
  copies: number;
  savedBytes: number;
  savedMb: number;
};

export type PastebinResponse = { url: string };

export type TrayDownloadStatus = {
  active: boolean;
  percentage: number;
  status: string | null;
};

/**
 * Version metadata for display in the UI
 */
export type VersionMetadata = {
  id: string;
  javaVersion: number | null;
  isInstalled: boolean;
};
