// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata for resumable downloads stored in .part.meta file
 */
export type DownloadMetadata = {
  url: string;
  fileName: string;
  totalSize: number;
  downloadedBytes: number;
  checksum: string | null;
  timestamp: number;
  segments: Array<DownloadSegment>;
};

/**
 * Download queue for persistence
 */
export type DownloadQueue = { pendingDownloads: Array<PendingJavaDownload> };

/**
 * A download segment for multi-segment parallel downloading
 */
export type DownloadSegment = {
  start: number;
  end: number;
  downloaded: number;
  completed: boolean;
};

export type DownloadTask = {
  url: string;
  path: string;
  sha1: string | null;
  sha256: string | null;
};

/**
 * Progress event for Java download
 */
export type JavaDownloadProgress = {
  fileName: string;
  downloadedBytes: number;
  totalBytes: number;
  speedBytesPerSec: number;
  etaSeconds: number;
  status: string;
  percentage: number;
};

/**
 * Pending download task for queue persistence
 */
export type PendingJavaDownload = {
  majorVersion: number;
  imageType: string;
  downloadUrl: string;
  fileName: string;
  fileSize: number;
  checksum: string | null;
  installPath: string;
  createdAt: number;
};

export type ProgressEvent = {
  file: string;
  downloaded: number;
  total: number;
  status: string;
  completedFiles: number;
  totalFiles: number;
  totalDownloadedBytes: number;
};
