// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemoryAllocation = {
  totalMemoryMb: number;
  availableMemoryMb: number;
  reservedMemoryMb: number;
  targetMemoryMb: number;
  headroomMb: number;
  recommendedMinMb: number;
  recommendedMaxMb: number;
  appliedMinMb: number;
  appliedMaxMb: number;
  modCount: number;
  workload: MemoryWorkload;
  pressure: MemoryPressure;
  source: MemoryAllocationSource;
};

export type MemoryAllocationSource =
  | "automatic"
  | "global-manual"
  | "instance-override";

export type MemoryPressure = "healthy" | "constrained" | "critical";

export type MemoryWorkload = "vanilla" | "light" | "moderate" | "heavy";
