// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DetectedLauncher = {
  launcherType: string;
  instancesDir: string;
  instanceCount: number;
};

export type ImportableInstance = {
  sourcePath: string;
  name: string;
  minecraftVersion: string | null;
  modLoader: string | null;
  modLoaderVersion: string | null;
};
