// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModInfo = {
  fileName: string;
  filePath: string;
  enabled: boolean;
  fileSize: bigint;
  modName: string | null;
  modId: string | null;
  version: string | null;
  description: string | null;
  modLoader: string | null;
};
