// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JavaCatalog = { releases: Array<JavaReleaseInfo>, available_major_versions: Array<number>, lts_versions: Array<number>, cached_at: bigint, };

export type JavaDownloadInfo = { version: string, release_name: string, download_url: string, file_name: string, file_size: bigint, checksum: string | null, image_type: string, };

export type JavaInstallation = { path: string, version: string, arch: string, vendor: string, source: string, is_64bit: boolean, };

export type JavaReleaseInfo = { major_version: number, image_type: string, version: string, release_name: string, release_date: string | null, file_size: bigint, checksum: string | null, download_url: string, is_lts: boolean, is_available: boolean, architecture: string, };
