// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Java image type: JRE or JDK
 */
export type ImageType = "jre" | "jdk";

/**
 * Java catalog containing all available versions
 */
export type JavaCatalog = {
  releases: Array<JavaReleaseInfo>;
  availableMajorVersions: Array<number>;
  ltsVersions: Array<number>;
  cachedAt: bigint;
};

/**
 * Java download information from Adoptium
 */
export type JavaDownloadInfo = {
  version: string;
  releaseName: string;
  downloadUrl: string;
  fileName: string;
  fileSize: bigint;
  checksum: string | null;
  imageType: string;
};

export type JavaInstallation = {
  path: string;
  version: string;
  is64bit: boolean;
};

/**
 * Java release information for UI display
 */
export type JavaReleaseInfo = {
  majorVersion: number;
  imageType: string;
  version: string;
  releaseName: string;
  releaseDate: string | null;
  fileSize: bigint;
  checksum: string | null;
  downloadUrl: string;
  isLts: boolean;
  isAvailable: boolean;
  architecture: string;
};
